import type { Metadata } from "next";
import "./globals.css";
import { Navigation } from "./components/organisms/Navigation/Navigation";
import { AuthProvider } from "./context/AuthContext/AuthContext";
import { ThemeProvider } from "./context/themeContext/ThemeContext";
import { ContextProviders } from "./context/ContextProviders/ContextProviders";

export const metadata: Metadata = {
  title: "Marbella Trends - Plages de Rêve, Clubs Branchés et Hôtel de Luxe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ContextProviders>
          <Navigation />
          {children}
        </ContextProviders>
      </body>
    </html>
  );
}
